version: "3.9"

services:

  flow_manager:
    image: flow_manager:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    ports:
      - "8000:8000" 
    volumes:
      - /etc/letsencrypt/fullchain.pem:/run/certs/fullchain.pem:ro
      - /etc/letsencrypt/privkey.pem:/run/certs/privkey.pem:ro
      - ./flow_manager/flows:/app/flows:ro
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=ethel_files
      - SSL_CERT_PATH=/run/certs/fullchain.pem
      - SSL_KEY_PATH=/run/certs/privkey.pem
      - SSL_PORT=8000

  reasoning_completion:
    image: reasoning_completion:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    env_file:
      - ./secret/.env
      - ./secret/reasoning_completion/.env

  emb_ada3large:
    image: emb_ada3large:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    env_file:
      - ./secret/.env
      - ./secret/emb_ada3large/.env

  file_to_text:
    image: file_to_text:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=ethel_files

  chunk_text:
    image: chunk_text:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    environment:
      - CHUNK_SIZE=2000
      - CHUNK_OVERLAP=400

  store_vectors:
    image: store_vectors:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    environment:
      - CHROMA_BASE_DIR=/chroma_db
    volumes:
      - /var/lib/ethel/chroma_db:/chroma_db

  emb_similarity_ada3large:
    image: emb_similarity_ada3large:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    networks:
      - ethel_net
    environment:
      - CHROMA_BASE_DIR=/chroma_db
    volumes:
      - /var/lib/ethel/chroma_db:/chroma_db

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      TZ: "UTC"
    networks:
      - ethel_net


networks:
  ethel_net:
    driver: overlay

volumes:
  mongo_data:
