#!/bin/bash

# Check if exactly one argument is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 [up|down|ps|flush|log] {service_name}"
    exit 1
fi

# Perform action based on the argument
case $1 in
    up)
        echo "Deploying flow stack..."
        docker stack deploy -c docker-compose.yml ethelflow
        ;;
    down)
        echo "Removing flow stack..."
        docker stack rm ethelflow
        ;;
    ps)
        echo "Listing services in the flow stack..."
        docker stack ps ethelflow --no-trunc
        ;;
    flush)
        echo "Restarting everything..."
        systemctl restart docker
        ;;
    log)
	echo "Log for ethelflow_$2"
        docker service logs ethelflow_$2
	;;
    *)
        echo "Invalid argument: $1"
        echo "Usage: $0 [up|down|ps|flush]"
        exit 2
        ;;
esac
