bazel_dep(name = "rules_oci", version = "2.2.6")
# For testing, we also recommend https://registry.bazel.build/modules/container_structure_test

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

# Declare external images you need to pull, for example:
oci.pull(
    name = "distroless_base",
    # 'latest' is not reproducible, but it's convenient.
    # During the build we print a WARNING message that includes recommended 'digest' and 'platforms'
    # values which you can use here in place of 'tag' to pin for reproducibility.
    tag = "latest",
    image = "gcr.io/distroless/base",
    platforms = ["linux/amd64"],
)

# For each oci.pull call, repeat the "name" here to expose them as dependencies.
use_repo(oci, "distroless_base")

bazel_dep(name = "rules_python", version = "1.4.1")
# bazel_dep(name = "rules_python_gazelle_plugin", version = "0.22.0")
# bazel_dep(name = "gazelle", version = "0.43.0", repo_name = "bazel_gazelle")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
python = use_extension("@rules_python//python/extensions:python.bzl", "python")

python.toolchain(
    python_version = "3.13.2",
)

pip.parse(
    hub_name = "pypi",
    python_version = "3.13.2",
    requirements_lock = "//:requirements_lock.txt",
)

use_repo(pip, "pypi")
bazel_dep(name = "rules_uv", version = "0.71.0")
